from fastapi import FastAPI
from pydantic import BaseModel
from typing import List, Optional
import uvicorn
from .cost_control import cost_guard, model_router

app = FastAPI(title="A2UI Production Agent Ops")

class A2UIComponent(BaseModel):
    type: str
    props: dict
    children: Optional[List['A2UIComponent']] = None

class A2UISurface(BaseModel):
    surfaceId: str
    content: List[A2UIComponent]

# Sample A2UI Generator
def generate_dashboard(query: str) -> A2UISurface:
    return A2UISurface(
        surfaceId="dynamic-response",
        content=[
            A2UIComponent(
                type="Text", 
                props={"text": f"Agent Response for: {query}", "variant": "h1"}
            ),
            A2UIComponent(
                type="Card",
                props={"title": "Analysis Result"},
                children=[
                    A2UIComponent(type="Text", props={"text": "This UI was generated by a live Python backend agent using ADK patterns.", "variant": "body"})
                ]
            )
        ]
    )

@app.get("/agent/query")
@cost_guard(budget_limit=0.10)
async def chat(q: str):
    """Simulates an ADK agent generating UI response with cost tracking."""
    model, reason = model_router(q)
    print(f"🤖 Routing to {model}: {reason}")
    return generate_dashboard(q)

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)
